### ISSUE TITLE
Amethyst_ui Tracker

### ISSUE THREAD

**Issue by grzi** [grzi/amethyst#1]
Okay, so to keep a track on what remains on the amethyst_ui transition to legion, here is a simple tracker issue.
Once errors are gone, I'll be able to make some unit tests & validate features

- [x] lib.rs
- [x] blink.rs
- [x] bundle.rs
- [x] button/mod.rs
- [x] button/actions.rs
- [x] button/builder.rs
- [x] button/retrigger.rs
- [x] button/system.rs
- [x] drag.rs
- [x] event.rs
- [x] event_retrigger.rs
- [x] format.rs
- [x] glyphs.rs
- [x] image.rs
- [x] label.rs
- [x] layout.rs
- [x] pass.rs
- [ ] ~~prefab.rs~~ Needs to be done after amethyst_asset's prefab
- [x] resize.rs
- [x] selection.rs
- [x] selection_order_cache.rs
- [x] sound.rs
- [x] text.rs
- [x] text_editing.rs
- [x] transforms.rs
- [x] widgets.rs

**Imports && port stuff :** 
~~73 errors remaining~~ ~~71 errors remaining~~ ~~70 errors remaining~~ ~~67 errors remaining~~ ~~65 errors remaining~~ ~~63 errors remaining~~ ~~61 errors remaining~~ ~~55 errors remaining~~ ~~52 errors remaining~~ ~~32 errors remaining~~ ~~29 errors remaining~~ ~~25 errors remaining~~ ~~23 errors remaining~~ ~~21 errors remaining~~ ~~14 errors remaining~~ ~~11 errors remaining~~ ~~10 errors remaining~~ ~~6 errors remaining~~ ~~5 errors remaining~~
0 errors remainings

**Real compilation errors :** 
~~164 errors remaining~~
~~118 errors remaining~~
~~119 errors remaining (:laughing:)~~
~~96 errors remaining~~
~~90 errors remaining~~
~~55 errors remaining~~
~~19 errors remaining~~
0 errors remainings

**Systems to check :**

- [x] ui_transform_system
- [x] ui_mouse_system
- [x] cache_selection_system
- [x] selection_mouse_system
- [x] selection_keyboard_system
- [x] text_editing_mouse_system
- [x] text_editing_input_system
- [x] resize_system
- [x] ui_button_system
- [x] drag_widget_system
- [x] button_action_retrigger_system
- [x] ui_sound_system
- [x] ui_sound_retrigger_system
- [x] blink_system
- [x] pass
- [x] builders

**Remaining notes to check :**
- [ ] ~~unit tests for each system~~
- [ ] replace the query.iter.filter I've used by query.get(*world, *entity).ok() || query.get(*world, *entity).is_ok()
- [x] get_parent_pixel_size in transform.rs should be fixed
- [x] Compute a different name from T for the EventRetriggerSystem
- [x] replace the build_xxx_system by a method taking world/resources to init system's resources
- [ ] should we use macro #[system] in our internal systems ? I think yes. But first unit test, then I'll see to convert

**Comment by grzi** [comment]
Converted sound.rs in 113188f

**Comment by grzi** [comment]
'Converted' image.rs (just removed component trait impl) in b29989b

**Comment by grzi** [comment]
Converted event.rs in 404256c

**Comment by grzi** [comment]
'Converted' format.rs in 666f9db

**Comment by grzi** [comment]
Converted transform.rs in ee7851a

**Comment by grzi** [comment]
Converted Button/retrigger.rs, Button/action.rs, Button/system.rs in be2cfeb

**Comment by grzi** [comment]
button/Builder.rs will be a tough one. Stopping it for today, will make progress this week end

**Comment by CleanCut** [comment]
Thanks, @grzi! Let us know when you're ready for a review. 😄

**Comment by grzi** [comment]
Converted resize in f55e150

**Comment by grzi** [comment]
Converted widget in b699886

**Comment by grzi** [comment]
Converted button/mod.rs and button/builder.rs in 9de3fbb

**Comment by grzi** [comment]
Converted drag.rs in 3513c3a

**Comment by grzi** [comment]
Converted glyphs.rs in 31354d8

**Comment by grzi** [comment]
Converted pass.rs in b82a19e

**Comment by grzi** [comment]
Come to a point where I need https://github.com/amethyst/amethyst/pull/2520/files or at least a full asset port

**Comment by grzi** [comment]
Decided to comment module prefab for now, if I manage to finish amethyst_ui before assets gets merged, I'll make sure to say it to the team

**Comment by grzi** [comment]
Converted label in bc7debf

**Comment by grzi** [comment]
Converted text-editings in 5190dba

**Comment by CleanCut** [comment]
> Come to a point where I need https://github.com/amethyst/amethyst/pull/2520/files or at least a full asset port

https://github.com/amethyst/serde-diff/pull/22 should hopefully allow the asset system work to proceed forward, once those folks have time to work on it again.

**Comment by grzi** [comment]
> > Come to a point where I need https://github.com/amethyst/amethyst/pull/2520/files or at least a full asset port
> 
> https://github.com/amethyst/serde-diff/pull/22 should hopefully allow the asset system work to proceed forward, once those folks have time to work on it again.

Yeah, just put in my todo list to check your PR. Thanks for that !

**Comment by grzi** [comment]
Converted selection_order_cache.rs in 69394a6

**Comment by grzi** [comment]
Converted selection.rs in ead26d0

**Comment by grzi** [comment]
Converted layout in 3bd72d3

**Comment by grzi** [comment]
Converted bundle (empty bundle and skip prefab for now) in 6955c26

**Comment by grzi** [comment]
Port is done, now I can see all the mistakes I've made from my port. 164 errors to handle. Seems like I've made a lot ahahah

**Comment by grzi** [comment]
Mostly miss about tuple / lifetimes to handle.

**Comment by grzi** [comment]
Note to myself, glyphs.rs was using z value of the glyphs to link entity, converting entity.id to f32.

Now that we don't have access to the real id, and moreover it's a u64, I'll create a Hashmap to store the link between glyphs and entities, if needed.

**Comment by grzi** [comment]
:tada: :tada: :tada:  Got the module amethyst_ui compiling with 1af0d48 :tada: :tada: :tada: 

Not meaning it works though, but it's compiling so now I can test
I'll just handle warnings before that

**Comment by grzi** [comment]
I've re-add systems to the ui bundle. Currently handling warnings (docs mainly) to be clean. Then I'll see how to test all of this

**Comment by grzi** [comment]
I've modified ui example to have something running. I'm testing the different systems. mouse_system is working

**Comment by grzi** [comment]
Time to 🛏️ 

Made a button with :hover to test ui_button_system and button_action_retrigger_system.
Works fine :

![ezgif-6-a284ab24a8db](https://user-images.githubusercontent.com/43185161/102418750-a5276e80-3ffe-11eb-831c-ffe35dc625ba.gif)

**Comment by grzi** [comment]
So, Text on button is working but the anchor/transform not working for now : 

<img width="407" alt="Capture d’écran 2020-12-18 à 00 57 09" src="https://user-images.githubusercontent.com/43185161/102557712-1d0f9a80-40cc-11eb-93a9-710eaeef0a09.png">

Strange behaviour.

**Comment by grzi** [comment]
Got it working The global request was uiTransform with Parent instead of with Children. 

![Screenshot from 2020-12-18 13-07-49](https://user-images.githubusercontent.com/43185161/102613017-0dc33800-4132-11eb-860e-cca5d39e1785.png)

**Comment by grzi** [comment]
Got the hover working. That was coming from a bad linkage between Transform and Parent/Childrent from amethyst core. I add to manually add a default Transform component to UiText/UiImage. This will be fixed later by using legion_transform

**Comment by grzi** [comment]
Complex BTN with sound, press & hover sound, hover & press text, cutom font, hover & press image all OK.
UiImage with texture OK

Currently debugging draggable

**Comment by grzi** [comment]
Got Draggable working, that was just a dereferencing issue

**Comment by grzi** [comment]
Got all working
Now I need to transtlate the systems to Parallel Runnable, I'm struggling with this
